### ISSUE TITLE
Windows Build of Release 0.3.4 is not working

### ISSUE THREAD

**Issue by itshorty** [r4sas/PBinCLI#38]
Hi!

Unfurtunaly the Windows Binary of Release #0.3.4 is not working if called without parameters

This happens if I execute it without any parameters:
 ```
.\pbincli-0.3.4.exe
Traceback (most recent call last):
  File "D:\devel\project\PrivateBin\PBinCLI\pbincli\cli.py", line 167, in <module>
  File "D:\devel\project\PrivateBin\PBinCLI\pbincli\cli.py", line 154, in main
AttributeError: 'Namespace' object has no attribute 'debug'
[17928] Failed to execute script 'cli' due to unhandled exception!
```

If I add all parameters needed for a send it works:
```
.\pbincli-0.3.4.exe send --burn -t "Test"
Preparing paste…
Uploading paste…
Paste uploaded!
PasteID:        cb65a960790821bc
Password:       GqDwv2FSR9eQS1dCTDvkmS6rdnGxMtGzSQj3eHMdAW3T
Delete token:   dfbb2a19b42c8620498a0c358f8b372550f337bab55ea97790cfe738d70ded25

Link:           https://paste.i2pd.xyz/?cb65a960790821bc#GqDwv2FSR9eQS1dCTDvkmS6rdnGxMtGzSQj3eHMdAW3T
Delete Link:    https://paste.i2pd.xyz/?pasteid=cb65a960790821bc&deletetoken=dfbb2a19b42c8620498a0c358f8b372550f337bab55ea97790cfe738d70ded25
```

**Comment by r4sas** [comment]
Hello. Thank you for reporting this. Looks like I messed up with available options when no command is provided.

**Comment by r4sas** [comment]
0.3.5 pushed.
